spring:
  application:
    name: course-service

server:
  port: 8075

logging:
  level:
    com.netflix.discovery: 'OFF'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/